# Generated by Django 2.2.6 on 2019-10-02 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=120, verbose_name='Bike name')),
                ('bike_model', models.CharField(max_length=120, verbose_name='Bike model')),
                ('bike_horsepower', models.IntegerField(validators=[django.core.validators.MinValueValidator(75), django.core.validators.MaxValueValidator(1250)])),
                ('bike_description', models.TextField(blank=True, max_length=250)),
            ],
        ),
    ]
